# Generated by Django 6.0.4 on 2026-04-24 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravity', models.CharField(choices=[('system', 'System'), ('escalation', 'Escalation')], max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem_type', models.CharField(choices=[('Configuration_reseau', 'Configuration réseau'), ('Probleme_technique', 'Problème technique'), ('Telecel_Money', 'Problème avec Telecel Money'), ('MusiCool', 'Problème avec MusiCool'), ('Credit', 'Problème de crédit'), ('Autre', 'Autre')], default='Autre', max_length=255)),
                ('Message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='conversations.message')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
