# Generated by Django 6.0.4 on 2026-04-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Channel', models.CharField(max_length=255)),
                ('ChannelUserId', models.CharField(max_length=50)),
                ('ConversationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasa_clients', to='conversations.conversation')),
            ],
        ),
    ]
