# Generated by Django 6.0.4 on 2026-04-25 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='administrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('BOT_ACTIVE', 'Bot active'), ('ESCALATED', 'Escalated'), ('HUMAN_ACTIVE', 'Human active'), ('CLOSED', 'Closed')], default='BOT_ACTIVE', max_length=20),
        ),
    ]
